import { initializeApp } from "firebase/app";
import { getFirestore, collection, doc, setDoc, getDoc, addDoc, serverTimestamp } from "firebase/firestore";
import { getStorage, ref, uploadBytes, getDownloadURL } from "firebase/storage";
import { getAuth } from "firebase/auth";

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID,
  measurementId: process.env.FIREBASE_MEASUREMENT_ID
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const storage = getStorage(app);
const auth = getAuth(app);

export { app, db, storage, auth };

// ==========================================
// Collections Configuration
// ==========================================

export const collections = {
  THREAT_HISTORY: "threat_history",
  UPLOAD_LOGS: "upload_logs",
  USER_ROLES: "user_roles"
};

// ==========================================
// Firebase Service Helpers
// ==========================================

/**
 * Log a file upload event
 * @param {string} userId - ID of the user uploading the file
 * @param {string} fileName - Name of the uploaded file
 * @param {string} fileUrl - Storage URL of the uploaded file
 * @param {string} status - Status of the upload (e.g., 'pending', 'scanned', 'rejected')
 */
export async function logUpload(userId, fileName, fileUrl, status = 'pending') {
  try {
    const logsRef = collection(db, collections.UPLOAD_LOGS);
    await addDoc(logsRef, {
      userId,
      fileName,
      fileUrl,
      status,
      timestamp: serverTimestamp()
    });
  } catch (error) {
    console.error("Error logging upload: ", error);
    throw error;
  }
}

/**
 * Record threat history for a scanned document
 * @param {string} fileId - ID of the uploaded file document
 * @param {object} scanResults - Details of the malware scan
 * @param {string} riskLevel - Risk level ('low', 'medium', 'high', 'critical')
 * @param {string} geminiExplanation - Explanation generated by Gemini AI
 */
export async function recordThreatHistory(fileId, scanResults, riskLevel, geminiExplanation = null) {
  try {
    const threatRef = collection(db, collections.THREAT_HISTORY);
    await addDoc(threatRef, {
      fileId,
      scanResults,
      riskLevel,
      geminiExplanation,
      detectedAt: serverTimestamp()
    });
  } catch (error) {
    console.error("Error recording threat history: ", error);
    throw error;
  }
}

/**
 * Get the role of a specific user
 * @param {string} userId - ID of the user
 * @returns {Promise<string|null>} - The user's role (e.g., 'admin', 'analyst', 'user')
 */
export async function getUserRole(userId) {
  try {
    const roleDocRef = doc(db, collections.USER_ROLES, userId);
    const roleDoc = await getDoc(roleDocRef);
    if (roleDoc.exists()) {
      return roleDoc.data().role;
    }
    return null;
  } catch (error) {
    console.error("Error getting user role: ", error);
    throw error;
  }
}

/**
 * Set or update a user's role
 * @param {string} userId - ID of the user
 * @param {string} role - Role to assign (e.g., 'admin', 'analyst', 'user')
 */
export async function setUserRole(userId, role) {
  try {
    const roleDocRef = doc(db, collections.USER_ROLES, userId);
    await setDoc(roleDocRef, {
      role,
      updatedAt: serverTimestamp()
    }, { merge: true });
  } catch (error) {
    console.error("Error setting user role: ", error);
    throw error;
  }
}

/**
 * Upload a file to Firebase Storage
 * @param {File|Blob} file - The file to upload
 * @param {string} path - The path in storage (e.g., 'uploads/documents/file.pdf')
 * @returns {Promise<string>} - The download URL of the uploaded file
 */
export async function uploadFile(file, path) {
  try {
    const fileRef = ref(storage, path);
    const snapshot = await uploadBytes(fileRef, file);
    const downloadURL = await getDownloadURL(snapshot.ref);
    return downloadURL;
  } catch (error) {
    console.error("Error uploading file: ", error);
    throw error;
  }
}
